### PR TITLE
Enables iterating over index endpoint results in a given block

### PR DESCRIPTION
**Pull request by eikes**
In stead of creating a very large array I would prefer to iterate over the results directly.

### CODE REVIEW

**Comment by eikes** [comment]
This allows us to do the following:

```ruby
client = Ioki::PlatformClient.new
product = client.products.first
stations = client.stations(product, options: { auto_paginate: true }) do |station|
  puts station.id
end
```

**Comment by A5308Y** [comment]
LGTM. And sorry for the delay. I'll probably not be working on ioki-ruby this month.

**Review by A5308Y — APPROVED** [review]

**Comment by rmehner** [comment]
Sorry, didn't have the time earlier. Since we're not streaming, I don't really see the advantage and it loses the clearness of "each" in the call. But that might be just me. I'm not opposed to it, just wondering why this is better than good old ".each do", which signals iteration.

**Comment by eikes** [comment]
@rmehner The advantage is, that the `results` array is not created in its entirety, because it could become rather large. Instead each page is requested one by one and the results are yielded. So in a sense, this is a sort of streaming, but rather on a index page basis.

**Comment by rmehner** [comment]
> Instead each page is requested one by one and the results are yielded. 

I read that part of the code wrong. That makes a lot of sense indeed. Thanks for clarifying!

**Pull request merged**
