### PR TITLE
Operator Api | Add missing product feature flag

### PR DESCRIPTION
**Pull request by tom-ioki**
This PR will add the missing feature flag `:passenger_client_displays_stations_on_map` to the `Features` model.

### CODE REVIEW

**Review by pak-ioki — COMMENTED** [review]
I miss the specs

**Comment by tom-ioki** [comment]
> I miss the specs

Usually we don't add specs for the models. But I can add some 👍

**Comment by tom-ioki** [comment]
Added some specs and I've moved the feature flag to the Product model (this was requested by Andy)

**Review by pak-ioki — APPROVED** [review]
Nice one. Thank you for the specs

**Pull request merged**
